# Utiliser l'image officielle de Nginx
FROM nginx:alpine

# Copier le fichier HTML dans le répertoire de Nginx
COPY index.html /usr/share/nginx/html/index.html

# Copier le fichier CSS dans le répertoire de Nginx
COPY style.css /usr/share/nginx/html/style.css

# Exposer le port 80 pour le serveur Nginx
EXPOSE 80
