# Utiliser l'image officielle de Node.js
FROM node:16

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source dans le conteneur
COPY . .

# Exposer le port sur lequel l'app écoute
EXPOSE 3000

# Démarrer l'application
CMD ["node", "app.js"]
